
---
- hosts: all
  become: no
  tasks:
  - name: line
    ansible.builtin.lineinfile:
      path: /tmp/semaphore.log
      line: This was written by semaphore at {{ ansible_date_time.iso8601 }}, {{var1}}
      create: yes
